# Generated by Django 2.2.17 on 2021-07-26 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
