# Generated by Django 2.2.17 on 2021-07-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0002_auto_20210726_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofileinfo',
            name='password',
            field=models.CharField(default='', max_length=4),
        ),
    ]
