# Generated by Django 3.2.5 on 2021-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0003_advertiserprofileinfo_citycorporationprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserprofileinfo',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='citycorporationprofileinfo',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customerprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='advertiserprofileinfo',
            name='Advertiser_profile_pic',
            field=models.ImageField(blank=True, default='/profiles_pic/Advertiser_profile_pic/demo_profile_pic2.png', upload_to='profiles_pic'),
        ),
        migrations.AddField(
            model_name='citycorporationprofileinfo',
            name='cityCor_profile_pic',
            field=models.ImageField(blank=True, default='/profiles_pic/cityCor_profile_pic/demo_profile_pic2.png', upload_to='profiles_pic'),
        ),
        migrations.AddField(
            model_name='customerprofileinfo',
            name='Customer_profile_pic',
            field=models.ImageField(blank=True, default='/profiles_pic/Customer_profile_pic/demo_profile_pic2.png', upload_to='profiles_pic'),
        ),
    ]
