# Generated by Django 2.2.17 on 2021-07-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0003_customerprofileinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofileinfo',
            name='password',
        ),
    ]
