# Generated by Django 3.2 on 2021-07-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0004_auto_20210707_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Advertise_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Spec_loc', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
