# Generated by Django 2.2.17 on 2021-09-11 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0004_auto_20210901_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserprofileinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='confirm_post',
            name='advertiser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adPoster2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confirm_post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currentpriceupdate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postadvertisetable',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adPoster', to=settings.AUTH_USER_MODEL),
        ),
    ]
