# Generated by Django 2.2.17 on 2021-07-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0005_auto_20210728_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserprofileinfo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='advertiserprofileinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='advertiserprofileinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='advertiserprofileinfo',
            name='location',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='advertiserprofileinfo',
            name='mobileNo',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='location',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='mobileNo',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='location',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='mobileNo',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
    ]
