# Generated by Django 3.2 on 2021-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0005_post_advertise_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_advertise_table',
            name='short_desc',
            field=models.TextField(max_length=100),
        ),
    ]
