# Generated by Django 2.2.17 on 2021-09-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0005_auto_20210911_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_post',
            name='advertiser',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
