# Generated by Django 2.2.17 on 2021-07-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0006_auto_20210729_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_advertise_table',
            name='height',
            field=models.PositiveIntegerField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post_advertise_table',
            name='width',
            field=models.PositiveIntegerField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post_advertise_table',
            name='size',
            field=models.PositiveIntegerField(default='', max_length=100),
        ),
    ]
