# Generated by Django 3.2.5 on 2021-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0007_auto_20210721_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserprofileinfo',
            name='is_advertiser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citycorporationprofileinfo',
            name='is_cityCor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofileinfo',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
