# Generated by Django 2.2.17 on 2021-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0007_auto_20210730_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_advertise_table',
            name='location',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post_advertise_table',
            name='height',
            field=models.FloatField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='post_advertise_table',
            name='short_desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post_advertise_table',
            name='size',
            field=models.FloatField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='post_advertise_table',
            name='width',
            field=models.FloatField(default='0', max_length=100),
        ),
    ]
