# Generated by Django 3.2.5 on 2021-07-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
