# Generated by Django 3.2.5 on 2021-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0010_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='is_cityCor',
            field=models.BooleanField(),
        ),
    ]
