# Generated by Django 3.2.5 on 2021-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0011_alter_citycorporationprofileinfo_is_citycor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycorporationprofileinfo',
            name='is_cityCor',
            field=models.BooleanField(default=False),
        ),
    ]
