# Generated by Django 3.2.5 on 2021-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0012_alter_citycorporationprofileinfo_is_citycor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='is_customer',
            field=models.BooleanField(),
        ),
    ]
