# Generated by Django 3.2.5 on 2021-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0013_alter_customerprofileinfo_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_advertise_table',
            name='posted_billboards_pic',
            field=models.ImageField(blank=True, default='/posted_billboards_pic/billboards_images/demo_billboard_image.JPG', upload_to='posted_billboards_pic'),
        ),
        migrations.AlterField(
            model_name='customerprofileinfo',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
