# Generated by Django 3.2.5 on 2021-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0014_auto_20210723_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_advertise_table',
            name='posted_billboards_pic',
            field=models.ImageField(blank=True, default='/posted_billboards_pic/billboards_images/demo_billboard_image.jpg', upload_to='posted_billboards_pic'),
        ),
    ]
