# Generated by Django 3.2.5 on 2021-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0015_alter_post_advertise_table_posted_billboards_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_advertise_table',
            name='posted_billboards_pic',
            field=models.ImageField(blank=True, default='/posted_billboards_pic/billboards_images/demo_billboard_image.JPG', upload_to='posted_billboards_pic'),
        ),
    ]
