# Generated by Django 3.2 on 2021-07-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0018_post_advertise_table_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_advertise_table',
            name='author',
        ),
    ]
