# Generated by Django 3.2 on 2021-07-30 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0020_post_advertise_table_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_advertise_table',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Billboard_Advertisement.advertiserprofileinfo'),
        ),
    ]
