# Generated by Django 3.2 on 2021-07-30 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Billboard_Advertisement', '0021_alter_post_advertise_table_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_advertise_table',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
