# Generated by Django 2.2.17 on 2021-10-01 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0022_auto_20211001_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm_post',
            name='confirmed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
