# Generated by Django 3.2 on 2021-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0025_post_advertise_table_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_post',
            name='adCode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post_advertise_table',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
