# Generated by Django 2.2.17 on 2021-08-28 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPriceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur'), ('Mars', 'Mars')], default='', max_length=30)),
                ('current_price', models.FloatField(default='0', max_length=10000)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PostAdvertiseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur'), ('Mars', 'Mars')], default='', max_length=30)),
                ('Spec_loc', models.CharField(default=None, max_length=100)),
                ('width', models.FloatField(default='0', max_length=100)),
                ('height', models.FloatField(default='0', max_length=100)),
                ('size', models.FloatField(default='0', max_length=100)),
                ('price', models.CharField(default=None, max_length=100)),
                ('short_desc', models.TextField(default=None, max_length=500)),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('posted_billboards_pic', models.ImageField(blank=True, default='/posted_billboards_pic/billboards_images/demo_billboard_image.JPG', upload_to='posted_billboards_pic/billboards_images')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur'), ('Mars', 'Mars')], default='', max_length=30, null=True)),
                ('mobileNo', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='/profiles_pic/Customer_profile_pic/demo_profile_pic2.png', upload_to='profiles_pic/Customer_profile_pic/')),
                ('is_customer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='confirm_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('adCode', models.CharField(max_length=100, unique=True)),
                ('advertiser', models.CharField(default=None, max_length=100)),
                ('confirmed_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CityCorporationProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur'), ('Mars', 'Mars')], default='', max_length=30, null=True)),
                ('mobileNo', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='/profiles_pic/cityCor_profile_pic/demo_profile_pic2.png', upload_to='profiles_pic/cityCor_profile_pic')),
                ('is_cityCor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Narayanganj', 'Narayanganj'), ('Gazipur', 'Gazipur'), ('Cumilla', 'Cumilla'), ('Chittagong', 'Chittagong'), ('Noakhali', 'Noakhali'), ('Jessore', 'Jessore'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Feni', 'Feni'), ('Pabna', 'Pabna'), ('Faridpur', 'Faridpur'), ('Dinajpur', 'Dinajpur'), ('Coxs Bazar', 'Coxs Bazar'), ('Bogra', 'Bogra'), ('Tangail', 'Tangail'), ('Patuakhali', 'Patuakhali'), ('Lalmonirhat', 'Lalmonirhat'), ('Madaripur', 'Madaripur'), ('Naogaon', 'Naogaon'), ('Rajbari', 'Rajbari'), ('Narail', 'Narail'), ('Pirojpur', 'Pirojpur'), ('Sherpur', 'Sherpur'), ('Mars', 'Mars')], default='', max_length=30, null=True)),
                ('mobileNo', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='/profiles_pic/Advertiser_profile_pic/demo_profile_pic2.png', upload_to='profiles_pic/Advertiser_profile_pic/')),
                ('is_advertiser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
