# Generated by Django 2.2.17 on 2021-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billboard_Advertisement', '0008_remove_advertiserprofileinfo_num_of_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirm_post',
            name='day',
        ),
        migrations.RemoveField(
            model_name='confirm_post',
            name='month',
        ),
        migrations.RemoveField(
            model_name='confirm_post',
            name='year',
        ),
        migrations.AddField(
            model_name='confirm_post',
            name='dealDuration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
